title = "CrossHub conf"

repo_root = ""

contract = "0x737217d6768E96fee112c16a0A9DcF0af5d56979"

rpcip = "192.168.3.137"

rpcport = "8545"

[port]
  grpc = 60012
  gateway = 9091

[gateway]
    allowed_origins = ["*"]

[cert]
  verify = true

[order]
  plugin = "plugins/raft.so"

[fabric]
  user = "User1"
  channelid = "mychannel"
  chaincodeid = "mycc"
  peerurl = "grpcs://localhost:7051"
  configpath = "./nodes/node2/org1sdk-config.yaml"
  events = "precommit,commit"
  datadir = "./nodes/node2/courier_data"
