title = "CrossHub conf"

role = 1

repo_root = ""

contract = "0x737217d6768E96fee112c16a0A9DcF0af5d56979"

rpcip = "192.168.3.137"

rpcport = "8545"

[port]
  grpc = 60012
  gateway = 9091

[gateway]
    allowed_origins = ["*"]

[cert]
  verify = true

[order]
  plugin = "plugins/raft.so"
