title = "CrossHub conf"

role = 1

repo_root = ""

contract = "0x71B4B8fd103dcDA2b971b1677ec70a96Ad24FB38"

rpcip = "192.168.3.137"

rpcport = "8545"

[port]
  grpc = 60012
  gateway = 9091

[gateway]
    allowed_origins = ["*"]

[cert]
  verify = true

[order]
  plugin = "plugins/raft.so"
